// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHJemSVqbAM2eUnKZaPeeCkjogUeyPoFE',
    appId: '1:710272464629:web:2e34b18ca2c799e40f77bc',
    messagingSenderId: '710272464629',
    projectId: 'trust-issues-v1',
    authDomain: 'trust-issues-v1.firebaseapp.com',
    storageBucket: 'trust-issues-v1.firebasestorage.app',
    measurementId: 'G-T3V998J3KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwyMq-0nOPE2z1twiCyi8fp0id3HM4zHc',
    appId: '1:710272464629:android:7fc80fcd45b30f7b0f77bc',
    messagingSenderId: '710272464629',
    projectId: 'trust-issues-v1',
    storageBucket: 'trust-issues-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn_PjW_8jX7vE9joXIfDnQo60-vONaehs',
    appId: '1:710272464629:ios:df08fe1593f416ac0f77bc',
    messagingSenderId: '710272464629',
    projectId: 'trust-issues-v1',
    storageBucket: 'trust-issues-v1.firebasestorage.app',
    iosClientId: '710272464629-su7ovpgigjtm36afbmu6ikmfo6k5hgtg.apps.googleusercontent.com',
    iosBundleId: 'com.example.trustIssuesMob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn_PjW_8jX7vE9joXIfDnQo60-vONaehs',
    appId: '1:710272464629:ios:df08fe1593f416ac0f77bc',
    messagingSenderId: '710272464629',
    projectId: 'trust-issues-v1',
    storageBucket: 'trust-issues-v1.firebasestorage.app',
    iosClientId: '710272464629-su7ovpgigjtm36afbmu6ikmfo6k5hgtg.apps.googleusercontent.com',
    iosBundleId: 'com.example.trustIssuesMob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHJemSVqbAM2eUnKZaPeeCkjogUeyPoFE',
    appId: '1:710272464629:web:2e34b18ca2c799e40f77bc',
    messagingSenderId: '710272464629',
    projectId: 'trust-issues-v1',
    authDomain: 'trust-issues-v1.firebaseapp.com',
    storageBucket: 'trust-issues-v1.firebasestorage.app',
    measurementId: 'G-T3V998J3KZ',
  );

}